name: generate ASCII
on: 
  push
jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v4
      - name: list file
        run: ls -ltar
      - name: running ascii.sh
        run: |
          chmod +x ascii.sh
          ./ascii.sh
          
