name: action-test
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: welcome message
      run: | 
        echo "welcome to github actions"
        ls -la
        cat README.md
    - name: Generate ASCII artwork
      run: |
        cowsay -f dragon "I am a dragon" >> art.txt
