name: action-test
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: welcome message
      run: echo "welcome to github actions"
    - name: list files
      run: ls -l
    - name: read README.md
      run: cat README.md
