name: multi-job
on: 
  push

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install cowsay
        run: sudo apt install cowsay -y
        
      - name: running cowsay command
        run: cowsay -f dragon "Hi" >> art.txt

      - name: upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: art
          path: art.txt
    
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download build artifact
        uses: actions/download-artifact@v4
        with:
          name: art

      -  name: checking if file exists
         run: ls -l | grep art.txt
  
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: download build artifact
        uses: actions/download-artifact@v4
        with:
          name: art
          
      -  name: print to screen
         run: cat art.txt
         
      -  name: deploy
         run: echo "deploying....."
