name: workflow-with-env-variables
on: 
  push

jobs:
  build_and_save:
    runs-on: ubuntu-latest
    steps: 
      -  name: puling nginx
         run: |
           docker pull nginx:latest
           
      -  name: saving docker images as tar
         run: docker save nginx:latest -o image.tar

      - name: upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: image.tar
  
  login_and_push:
    needs: build_and_save
    runs-on: ubuntu-latest
    steps:
      -  name: login to docker
         run: docker login -u ${{ vars.USERNAME }} -p ${{ secrets.PASSWORD}}

      - name: download build artifact
        uses: actions/download-artifact@v4
        with:
          name: image
      
      -  name: load image
         run: docker image load -i image.tar
    
      -  name: push to docker
         run: |
          docker image tag nginx:latest ${{ vars.DOCKER_REGISTERY}}/${{ vars.USERNAME }}/${{ vars.REPO_NAME}}:latest
          docker push ${{ vars.DOCKER_REGISTERY}}/${{ vars.USERNAME }}/${{ vars.REPO_NAME}}:latest
