name: workflow-with-env-variables
on: 
  push
env:
  USERNAME: tusharthapliyal
  PASSWORD: Tushar_docker_8979
  REPO_NAME: action-test
  DOCKER_REGISTERY: docker.io
jobs:
  build_and_save:
    runs-on: ubuntu-latest
    steps: 
      -  name: puling nginx
         run: |
           docker pull nginx:latest
           docker image tag nginx:latest $DOCKER_REGISTERY/$USERNAME/$REPO_NAME:latest

      -  name: saving docker images as tar
         run: docker save $DOCKER_REGISTERY/$USERNAME/$REPO_NAME:latest -o $REPO_NAME.tar

      - name: upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: $REPO_NAME
          path: $REPO_NAME.txt
  
  login_and_push:
    needs: build_and_save
    runs-on: ubuntu-latest
    steps:
      -  name: login to docker
         run: docker login -u $USERNAME -p $PASSWORD

      - name: download build artifact
        uses: actions/download-artifact@v4
        with:
          name: $REPO_NAME
          
      -  name: push to docker
         run: docker push $DOCKER_REGISTERY/$USERNAME/$REPO_NAME:latest
